E-poles/Controllers/PolesController.cs
using AutoMapper;
using E_poles.Areas.admin.Models;
using E_poles.Dal;
using E_poles.Models.Pole;
using E_poles.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace E_poles.Controllers
{
    public class PolesController : Controller
    {
        IGroupService _groupService;
        IEpoleService _epoleService;
        private readonly UserManager<User> _userManager;
        private readonly IMapper _mapper;
        public PolesController(IGroupService groupService, UserManager<User> userManager, IEpoleService epoleService, IMapper mapper)
        {
            _mapper = mapper;
            _userManager = userManager;
            _groupService = groupService;
            _epoleService = epoleService;
        }

        public async Task<IActionResult> Index()
        {
            var cUser = await _userManager.GetUserAsync(User);
            var userGroups = await _groupService.GetGroupByUserId(cUser.Id);
            var model = new SrchPolesModel();
            var areaList = await _epoleService.GetAllArea(userGroups.GroupsId);
            model.AreaList = areaList.Select(x => new SelectListItem
            {
                Value = x.Area,
                Text = x.Area
            }).ToList();
            var streetList = await _epoleService.GetAllStreet(userGroups.GroupsId);
            model.StreetList = streetList.Select(x => new SelectListItem
            {
                Value = x.Street,
                Text = x.Street
            }).ToList();
            return View(model);
        }

        private async Task<IEnumerable<Poles>> GetAllPolesByGroupId(string userId)
        {
            var userGroups = await _groupService.GetGroupByUserId(int.Parse(userId));

            var result = await _epoleService.GetAll(userGroups.GroupsId);
            return result;
        }

        public async Task<IActionResult> GetDtPolesList([FromBody] SrchPolesModel model)
        {
            var result = await GetAllPolesByGroupId(model.UserId);

            var poleList = _mapper.Map<IEnumerable<PoleListModel>>(result);
            if (!String.IsNullOrEmpty(model.SelectedArea))
            {
                poleList = poleList.Where(s =>
                                     (s.Area != null && s.Area.Contains(model.SelectedArea))
                                    );
            }
            if (!String.IsNullOrEmpty(model.SelectedStreet))
            {
                poleList = poleList.Where(s =>
                                    (s.Street != null && s.Street.Contains(model.SelectedStreet)));
            }
            if (!String.IsNullOrEmpty(model.SelectedStatus))
            {
                var _status = Convert.ToBoolean(int.Parse(model.SelectedStatus));
                poleList = poleList.Where(w => w.Status == _status);
            }
            if (!String.IsNullOrEmpty(model.KeySearch))
            {
                poleList = poleList.Where(s =>
                                    (s.Name != null && s.Name.ToLower().Contains(model.KeySearch.ToLower())) ||
                                    (s.Area != null && s.Area.Contains(model.KeySearch)) ||
                                    (s.Street != null && s.Street.Contains(model.KeySearch)) ||
                                    (s.Note != null && s.Note.ToLower().Contains(model.KeySearch.ToLower())) ||
                                    (s.Description != null && s.Description.ToLower().Contains(model.KeySearch.ToLower()))
                                    );
            }

            int recordsTotal = poleList.Count();
            var data = poleList.Skip(model.Start).Take(model.Length);
            var jsonData = new { draw = model.Draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data };
            return Ok(jsonData);
            //return Json(new DtResult<Poles>
            //{
            //    Draw = dtParameters.Draw,
            //    RecordsTotal = result.Count(),
            //    RecordsFiltered = result.Count(),
            //    Data = result.Skip(dtParameters.Start)
            //        .Take(dtParameters.Length)
            //});
        }

    }
}

E-poles/Areas/admin/Views/Shared/_AdminLayout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Admin @ViewData["Title"] </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
    <meta name="msapplication-tap-highlight" content="no">
    <link href="~/css/admin/main.v2.css" rel="stylesheet" />
    <style>
        .app-footer-center {
            position: absolute;
            left: 12px;
            right: 12px;
            bottom: 4px;
            padding: 8px;
            line-height: 36px;
            border-top: 3px double #E5E5E5;
            text-align: center;
        }
    </style>
    <style>
        .ui-theme-settings .btn-open-options {
            bottom: 3px;
        }
    </style>
</head>
<body>
    <div class="app-container app-theme-white body-tabs-shadow fixed-header fixed-sidebar">
        <div class="app-header header-shadow">
            <div class="app-header__logo">
                <div class="logo-src"></div>
                <div class="header__pane ml-auto">
                    <div>
                        <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="app-header__mobile-menu">
                <div>
                    <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                    </button>
                </div>
            </div>
            <div class="app-header__menu">
                <span>
                    <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                        <span class="btn-icon-wrapper">
                            <i class="fa fa-ellipsis-v fa-w-6"></i>
                        </span>
                    </button>
                </span>
            </div>
            <div class="app-header__content">
                <div class="app-header-left">
                    <partial name="_HeaderMenuLeftPartial" />
                </div>
                <div class="app-header-right">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </div>
        <partial name="_ThemeSettingPartial" />
        <div class="app-main">
            <partial name="_LeftMenuPartial" />
            <div class="app-main__outer">
                <div class="app-main__inner">
                    @RenderBody()
                </div>
                <div class="app-wrapper-footer">
                    <div class="app-footer">
                        <div class="app-footer__inner">
                            <div class="app-footer-center">
                                &copy; 2021-2022 HTMP (HighWay Traffic Management Program), All rights reserved.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/js/admin/main.v2.js"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

E-poles/Areas/admin/Views/Shared/_HeaderMenuLeftPartial.cshtml
@*<div class="search-wrapper">
    <div class="input-holder">
        <input type="text" class="search-input" placeholder="Type to search">
        <button class="search-icon"><span></span></button>
    </div>
    <button class="close"></button>
</div>
<ul class="header-menu nav">
    <li class="nav-item">
        <a href="javascript:void(0);" class="nav-link">
            <i class="nav-link-icon fa fa-database"> </i>
            Statistics
        </a>
    </li>
    <li class="btn-group nav-item">
        <a href="javascript:void(0);" class="nav-link">
            <i class="nav-link-icon fa fa-edit"></i>
            Projects
        </a>
    </li>
    <li class="dropdown nav-item">
        <a href="javascript:void(0);" class="nav-link">
            <i class="nav-link-icon fa fa-cog"></i>
            Settings
        </a>
    </li>
</ul>*@

E-poles/Areas/admin/Views/Shared/_LeftMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using E_poles.Dal
@inject UserManager<User> UserManager
@{
    var cUser = await UserManager.GetUserAsync(User);
    var IsRoleSuperAdmin = await UserManager.IsInRoleAsync(cUser, "SuperAdministrator");
}
<div class="app-sidebar sidebar-shadow">
    <div class="app-header__logo">
        <div class="logo-src"></div>
        <div class="header__pane ml-auto">
            <div>
                <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                    </span>
                </button>
            </div>
        </div>
    </div>
    <div class="app-header__mobile-menu">
        <div>
            <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
            </button>
        </div>
    </div>
    <div class="app-header__menu">
        <span>
            <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                <span class="btn-icon-wrapper">
                    <i class="fa fa-ellipsis-v fa-w-6"></i>
                </span>
            </button>
        </span>
    </div>
    <div class="scrollbar-sidebar">
        <div class="app-sidebar__inner">
            <ul class="vertical-nav-menu">
                <li class="app-sidebar__heading"></li>
                <li>
                    <a asp-controller="Dashboard" asp-action="Index">
                        <i class="metismenu-icon pe-7s-rocket"></i>
                        Dashboard
                    </a>
                </li>
                <li class="app-sidebar__heading"></li>
                <li>
                    <a asp-controller="Poles" asp-action="Index">
                        <i class="metismenu-icon pe-7s-display2"></i>
                        Data Management
                    </a>
                </li>
                @if (IsRoleSuperAdmin)
                {
                    <li class="app-sidebar__heading"></li>
                    <li>
                        <a asp-controller="Groups" asp-action="Index">
                            <i class="metismenu-icon pe-7s-display2"></i>
                            Group Management
                        </a>
                    </li>
                    <li class="app-sidebar__heading"></li>
                    <li>
                        <a asp-controller="Users" asp-action="Index">
                            <i class="metismenu-icon pe-7s-display2"></i>
                            User Management
                        </a>
                    </li>
                }
                @*<li>
                        <a href="#">
                            <i class="metismenu-icon pe-7s-display2"></i>
                            Pole Management
                            <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
                        </a>
                        <ul>
                            <li>
                                <a asp-controller="Poles" asp-action="Index">
                                    <i class="metismenu-icon"></i>
                                    Poles List
                                </a>
                            </li>
                        </ul>
                    </li>*@
            </ul>
        </div>
    </div>
</div>